package com.sbi.surakshasathi.feature.messagefriction.presentation

import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.sbi.surakshasathi.app.navigation.Screen
import com.sbi.surakshasathi.core.common.Result
import com.sbi.surakshasathi.feature.messagefriction.domain.model.FrictionTrigger
import com.sbi.surakshasathi.feature.messagefriction.domain.usecase.QuarantineMessageUseCase
import com.sbi.surakshasathi.feature.messagescan.domain.model.Message
import com.sbi.surakshasathi.feature.messagescan.domain.repository.MessageRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

sealed interface MicroEducationUiState {
    data object Loading : MicroEducationUiState

    data class Content(val message: Message) : MicroEducationUiState

    data object Declined : MicroEducationUiState

    data object Continued : MicroEducationUiState

    data class Error(val message: String) : MicroEducationUiState
}

/**
 * Layer B of the Adaptive Friction engine — the specific, substantial (1-1.5 paragraph)
 * micro-lesson generated by the SAME backend call as the original RAG warning (see
 * `Rag_model/common/schemas.py:ThreatReport.micro_lesson`), not a second round trip. Reads it off
 * the already-persisted [Message] (see [MessageRepository.saveRagWarning]) rather than re-fetching
 * from the network.
 */
@HiltViewModel
class MicroEducationViewModel
    @Inject
    constructor(
        private val messageRepository: MessageRepository,
        private val quarantineMessageUseCase: QuarantineMessageUseCase,
        savedStateHandle: SavedStateHandle,
    ) : ViewModel() {
        val messageId: Long = savedStateHandle.get<String>("messageId")?.toLongOrNull() ?: -1L
        val trigger: FrictionTrigger =
            FrictionTrigger.from(
                tag = savedStateHandle.get<String>("triggerTag") ?: FrictionTrigger.TAG_GENERIC,
                url = Screen.decodeUrl(savedStateHandle.get<String>("url")),
            )

        private val _uiState = MutableStateFlow<MicroEducationUiState>(MicroEducationUiState.Loading)
        val uiState: StateFlow<MicroEducationUiState> = _uiState.asStateFlow()

        init {
            viewModelScope.launch {
                when (val result = messageRepository.getById(messageId)) {
                    is Result.Success -> _uiState.value = MicroEducationUiState.Content(result.data)
                    is Result.Error ->
                        _uiState.value = MicroEducationUiState.Error(result.error.message ?: "Unable to load this message")
                    is Result.Loading -> Unit
                }
            }
        }

        fun onDecline() {
            viewModelScope.launch { quarantineMessageUseCase.onDecline(messageId) }
            _uiState.value = MicroEducationUiState.Declined
        }

        fun onContinue() {
            _uiState.value = MicroEducationUiState.Continued
        }
    }
